import { createContract, getContracts, type BackendContract, type ContractCatalogs, type ContractPayload } from "@/api/client/contract.api";
import type { ArchivoContrato, Contrato, ContratoFormData } from "@/modules/contratos/types/contrato.types";
const FILE_DATABASE = "karfleet-contract-files"; const FILE_STORE = "files"; const META_KEY = "contract-file-metadata";
function metadata(): Record<string, ArchivoContrato> { try { return JSON.parse(localStorage.getItem(META_KEY) ?? "{}") as Record<string, ArchivoContrato>; } catch { return {}; } }
function openDatabase() { return new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(FILE_DATABASE, 1); request.onupgradeneeded = () => { if (!request.result.objectStoreNames.contains(FILE_STORE)) request.result.createObjectStore(FILE_STORE); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(new Error("No se pudo abrir el almacenamiento de archivos.")); }); }
async function saveFile(id: string, file: File) { const database = await openDatabase(); await new Promise<void>((resolve, reject) => { const transaction = database.transaction(FILE_STORE, "readwrite"); transaction.objectStore(FILE_STORE).put(file, id); transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(new Error("No se pudo guardar el archivo del contrato.")); }); database.close(); localStorage.setItem(META_KEY, JSON.stringify({ ...metadata(), [id]: { nombre: file.name, tipo: file.type, tamano: file.size } })); }
export async function getContratoFile(id: string) { const database = await openDatabase(); const file = await new Promise<File | undefined>((resolve, reject) => { const request = database.transaction(FILE_STORE).objectStore(FILE_STORE).get(id); request.onsuccess = () => resolve(request.result as File | undefined); request.onerror = () => reject(new Error("No se pudo recuperar el archivo.")); }); database.close(); return file; }
const dateOnly = (value: string) => value.slice(0, 10);
function normalize(item: BackendContract, catalogs: ContractCatalogs): Contrato { return { id: item.contractId, inversionistaId: item.investorId, vehiculoId: item.vehicleId, numeroContrato: item.contractNumber, catalogContractTypeId: item.catalogContractTypeId, tipoContrato: catalogs.types.find((type) => type.id === item.catalogContractTypeId)?.name ?? "Tipo no disponible", fechaInicio: dateOnly(item.startDate), fechaFin: dateOnly(item.endDate), montoMensual: String(item.monthlyAmount), montoCompra: String(item.purchaseAmount ?? 0), catalogContractStatusId: item.catalogContractStatusId, estado: catalogs.statuses.find((status) => status.id === item.catalogContractStatusId)?.name ?? "Estado no disponible", observaciones: item.notes ?? "", archivo: metadata()[item.contractId], createdAt: item.createdAt }; }
function payload(data: ContratoFormData): ContractPayload { return { vehicleId: data.vehiculoId, investorId: data.inversionistaId, catalogContractTypeId: data.catalogContractTypeId, startDate: new Date(data.fechaInicio).toISOString(), endDate: new Date(data.fechaFin).toISOString(), monthlyAmount: Number(data.montoMensual), ...(data.montoCompra ? { purchaseAmount: Number(data.montoCompra) } : {}), catalogContractStatusId: data.catalogContractStatusId, notes: data.observaciones?.trim() || undefined }; }
export async function getContratos(catalogs: ContractCatalogs) { return (await getContracts()).map((item) => normalize(item, catalogs)); }
export async function createContrato(data: ContratoFormData, catalogs: ContractCatalogs) { const created = await createContract(payload(data)); await saveFile(created.contractId, data.archivo); return normalize(created, catalogs); }
