"use client";
import { useEffect, useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Download, Eye, FileText, Pencil, Plus, Search, ShieldCheck, X } from "lucide-react";
import { SeguroForm } from "@/components/seguros/SeguroForm";
import { toast } from "@/components/ui/toast";
import { useVehiculos } from "@/modules/vehiculo/hooks/use-vehiculos";
import { useSeguros } from "@/modules/seguros/hooks/use-seguros";
import type { Seguro, SeguroFormData, SeguroStatus } from "@/modules/seguros/types/seguro.types";
import { formatDate, formatMoney, getSeguroStatus, SEGURO_STATUS_LABELS } from "@/modules/seguros/utils/seguro.utils";
import { exportSegurosToExcel } from "@/modules/seguros/services/seguro-excel.service";
import { exportSegurosToPdf } from "@/modules/seguros/services/seguro-pdf.service";

const PAGE_SIZE = 10;
const STATUS_STYLES: Record<SeguroStatus, string> = {
  vigente: "border-slate-300 bg-slate-100 text-slate-900",
  por_vencer: "border-amber-300 bg-amber-50 text-amber-800",
  vencido: "border-red-300 bg-red-50 text-red-700",
};
function catalogFromStorage() {
  const names = new Set<string>();
  for (const key of ["aseguradoras", "empresas"]) try { const values = JSON.parse(localStorage.getItem(key) ?? "[]") as Array<string | Record<string, unknown>>; values.forEach((v) => { const name = typeof v === "string" ? v : String(v.nombre ?? v.razonSocial ?? ""); if (name.trim()) names.add(name.trim()); }); } catch { /* catálogo aún no disponible */ }
  return [...names].sort((a, b) => a.localeCompare(b, "es"));
}

export default function SegurosPage() {
  const { vehiculos, isLoading: vehiclesLoading } = useVehiculos(); const { seguros, isLoading, error, addSeguro, editSeguro } = useSeguros();
  const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState<SeguroStatus | "todos">("todos"); const [page, setPage] = useState(1); const [formOpen, setFormOpen] = useState(false); const [selected, setSelected] = useState<Seguro>(); const [detail, setDetail] = useState<Seguro>(); const [exporting, setExporting] = useState<"excel" | "pdf">(); const [catalog, setCatalog] = useState<string[]>([]);
  useEffect(() => { // eslint-disable-next-line react-hooks/set-state-in-effect
    setCatalog(catalogFromStorage());
  }, []);
  useEffect(() => {
    const requestedId = new URLSearchParams(window.location.search).get("detalle");
    const requested = seguros.find((item) => item.id === requestedId);
    if (requested) { // eslint-disable-next-line react-hooks/set-state-in-effect
      setDetail(requested);
    }
  }, [seguros]);
  const insurers = useMemo(() => [...new Set([...catalog, ...seguros.map((s) => s.aseguradora).filter(Boolean)])].sort(), [catalog, seguros]);
  const plate = (id: string) => vehiculos.find((v) => v.id === id)?.placa ?? "Vehículo no disponible";
  const totals = useMemo(() => ({
    todos: seguros.length,
    vigente: seguros.filter((s) => getSeguroStatus(s.fechaFin) === "vigente").length,
    por_vencer: seguros.filter((s) => getSeguroStatus(s.fechaFin) === "por_vencer").length,
    vencido: seguros.filter((s) => getSeguroStatus(s.fechaFin) === "vencido").length,
  }), [seguros]);
  const filtered = useMemo(() => { const q = search.trim().toLocaleLowerCase("es-BO"); return seguros.filter((s) => (statusFilter === "todos" || getSeguroStatus(s.fechaFin) === statusFilter) && (!q || [vehiculos.find((v) => v.id === s.vehiculoId)?.placa ?? "", s.aseguradora, s.numeroPoliza ?? ""].some((v) => v.toLocaleLowerCase("es-BO").includes(q)))); }, [search, seguros, statusFilter, vehiculos]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const current = Math.min(page, totalPages); const visible = filtered.slice((current - 1) * PAGE_SIZE, current * PAGE_SIZE);
  const save = async (data: SeguroFormData) => { try { if (data.numeroPoliza && seguros.some((s) => s.id !== selected?.id && s.numeroPoliza?.toLowerCase() === data.numeroPoliza?.toLowerCase())) { toast.error("Ya existe un seguro con ese número de póliza"); return false; } if (selected) editSeguro(selected.id, data); else addSeguro(data); toast.success(selected ? "Seguro actualizado correctamente" : "Seguro registrado correctamente"); setSelected(undefined); return true; } catch (cause) { toast.error(cause instanceof Error ? cause.message : "No se pudo guardar el seguro."); return false; } };
  const runExport = async (kind: "excel" | "pdf") => { setExporting(kind); try { if (kind === "excel") await exportSegurosToExcel(seguros, vehiculos); else await exportSegurosToPdf(seguros, vehiculos); toast.success(`Reporte ${kind.toUpperCase()} generado correctamente`); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "No se pudo generar el reporte."); } finally { setExporting(undefined); } };
  return <div className="mx-auto w-full max-w-7xl space-y-5">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-semibold"><ShieldCheck />Seguros</h1><p className="mt-1 text-sm text-slate-500">Administra las pólizas asociadas a los vehículos.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => runExport("excel")} disabled={!!exporting} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold"><Download className="mr-2 inline h-4 w-4" />{exporting === "excel" ? "Generando…" : "Excel"}</button><button onClick={() => runExport("pdf")} disabled={!!exporting} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold"><FileText className="mr-2 inline h-4 w-4" />{exporting === "pdf" ? "Generando…" : "PDF"}</button><button onClick={() => { setSelected(undefined); setFormOpen(true); }} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="mr-2 inline h-4 w-4" />Nuevo seguro</button></div></header>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{([['todos', 'Total de seguros'], ['vigente', 'Activos'], ['por_vencer', 'Por vencerse'], ['vencido', 'Expirados']] as const).map(([key, label]) => <button key={key} type="button" onClick={() => { setStatusFilter(key); setPage(1); }} className={`rounded-2xl border bg-white p-4 text-left shadow-sm transition hover:border-slate-500 ${statusFilter === key ? "ring-2 ring-slate-900 ring-offset-1" : "border-slate-200"}`}><p className="text-sm font-medium text-slate-500">{label}</p><p className={`mt-1 text-2xl font-bold ${key === "por_vencer" ? "text-amber-700" : key === "vencido" ? "text-red-700" : "text-slate-950"}`}>{totals[key]}</p></button>)}</div>
    <section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-2 border-b p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input type="search" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Buscar por placa, aseguradora o N° de póliza" className="w-full rounded-xl border py-2.5 pl-9 pr-10 text-sm" /></label><select value={statusFilter} onChange={(e) => { setStatusFilter(e.target.value as SeguroStatus | "todos"); setPage(1); }} className="rounded-xl border bg-white px-3 py-2.5 text-sm"><option value="todos">Todos los estados</option><option value="vigente">Activos</option><option value="por_vencer">Por vencerse</option><option value="vencido">Expirados</option></select>{(search || statusFilter !== "todos") && <button onClick={() => { setSearch(""); setStatusFilter("todos"); setPage(1); }} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Limpiar</button>}</div>
      {(isLoading || vehiclesLoading) ? <div className="space-y-3 p-5" aria-label="Cargando seguros">{[1,2,3,4].map((i) => <div key={i} className="h-12 animate-pulse rounded bg-slate-100" />)}</div> : error ? <div className="p-10 text-center text-red-700">{error}</div> : !visible.length ? <div className="p-14 text-center"><ShieldCheck className="mx-auto text-slate-300" /><p className="mt-3 font-medium">{search || statusFilter !== "todos" ? "Sin resultados" : "No existen seguros registrados"}</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Vehículo", "Aseguradora", "N° de póliza", "Valor asegurado", "Franquicia", "Fecha de inicio", "Fecha de fin", "Estado", "Acciones"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{visible.map((s) => { const status = getSeguroStatus(s.fechaFin); return <tr key={s.id}><td className="px-4 py-3 font-semibold">{plate(s.vehiculoId)}</td><td className="px-4 py-3">{s.aseguradora}</td><td className="px-4 py-3">{s.numeroPoliza || "—"}</td><td className="px-4 py-3">{formatMoney(s.valorAsegurado)}</td><td className="px-4 py-3">{formatMoney(s.franquicia)}</td><td className="px-4 py-3">{formatDate(s.fechaInicio)}</td><td className="px-4 py-3">{formatDate(s.fechaFin)}</td><td className="px-4 py-3"><span className={`inline-flex whitespace-nowrap rounded-full border px-2.5 py-1 text-xs font-semibold ${STATUS_STYLES[status]}`}>{SEGURO_STATUS_LABELS[status]}</span></td><td className="px-4 py-3"><button onClick={() => setDetail(s)} aria-label="Ver detalle" className="p-2"><Eye className="h-4 w-4" /></button><button onClick={() => { setSelected(s); setFormOpen(true); }} aria-label="Editar" className="p-2"><Pencil className="h-4 w-4" /></button></td></tr>; })}</tbody></table></div>}
      {filtered.length > PAGE_SIZE && <footer className="flex items-center justify-between border-t p-4 text-sm"><span>{(current - 1) * PAGE_SIZE + 1}–{Math.min(current * PAGE_SIZE, filtered.length)} de {filtered.length}</span><div className="flex items-center gap-2"><button disabled={current === 1} onClick={() => setPage(current - 1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft className="h-4 w-4" /></button><span>Página {current} de {totalPages}</span><button disabled={current === totalPages} onClick={() => setPage(current + 1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight className="h-4 w-4" /></button></div></footer>}
    </section>
    {formOpen && <SeguroForm seguro={selected} vehiculos={vehiculos} aseguradoras={insurers} onSave={save} onClose={() => { setFormOpen(false); setSelected(undefined); }} />}
    {detail && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/50 p-4"><article className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6"><header className="flex justify-between"><h2 className="text-xl font-semibold">Detalle del seguro</h2><button onClick={() => setDetail(undefined)}><X /></button></header><dl className="mt-6 grid gap-5 sm:grid-cols-2">{[["Placa del vehículo", plate(detail.vehiculoId)], ["Aseguradora", detail.aseguradora], ["N° de póliza", detail.numeroPoliza || "—"], ["Valor asegurado", formatMoney(detail.valorAsegurado)], ["Franquicia", formatMoney(detail.franquicia)], ["Fecha de inicio", formatDate(detail.fechaInicio)], ["Fecha de fin", formatDate(detail.fechaFin)], ["Forma de pago", detail.modalidadPago === "credito" ? "Crédito" : "Contado"], ["Observaciones", detail.observaciones || "—"]].map(([label, value]) => <div key={label}><dt className="text-xs font-medium uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl>{detail.modalidadPago === "credito" && <section className="mt-6 rounded-xl border bg-slate-50 p-4"><h3 className="text-sm font-semibold">Plan de pagos mensuales</h3><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-2">Cuota</th><th className="py-2">Mes</th><th className="py-2 text-right">Monto</th></tr></thead><tbody>{detail.cuotas.map((cuota, index) => <tr key={cuota.id} className="border-b last:border-0"><td className="py-2">{index + 1}</td><td className="py-2">{new Intl.DateTimeFormat("es-BO", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${cuota.mes}-01T00:00:00Z`))}</td><td className="py-2 text-right font-semibold">{formatMoney(cuota.monto)}</td></tr>)}</tbody><tfoot><tr className="border-t-2"><td colSpan={2} className="pt-3 font-semibold">Total financiado</td><td className="pt-3 text-right font-bold">{formatMoney(String(detail.cuotas.reduce((sum, cuota) => sum + Number(cuota.monto), 0)))}</td></tr></tfoot></table></div></section>}<footer className="mt-7 flex justify-end gap-2"><button onClick={() => setDetail(undefined)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Volver</button><button onClick={() => { setSelected(detail); setDetail(undefined); setFormOpen(true); }} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Editar</button></footer></article></div>}
  </div>;
}
