"use client";
import { useState } from "react";
import { FileText, LoaderCircle, Upload, X } from "lucide-react";
import type { ContractCatalogs } from "@/api/client/contract.api";
import type { Inversionista } from "@/modules/inversionista/types/inversionista.types";
import type { Vehiculo } from "@/modules/vehiculo/types/vehiculo.types";
import type { ContratoFormData } from "@/modules/contratos/types/contrato.types";
const MAX_SIZE = 5 * 1024 * 1024; const FILE_TYPES = ["application/pdf", "image/jpeg", "image/png"];
type State = Omit<ContratoFormData, "archivo"> & { archivo?: File }; type Field = keyof State;
const fieldClass = (bad?: string) => `w-full rounded-xl border bg-white px-3.5 py-2.5 text-sm outline-none ${bad ? "border-red-500" : "border-slate-300 focus:border-slate-950"}`;
export function ContratoForm({ inversionistas, vehiculos, catalogs, onSave, onClose }: { inversionistas: Inversionista[]; vehiculos: Vehiculo[]; catalogs: ContractCatalogs; onSave: (data: ContratoFormData) => Promise<boolean>; onClose: () => void }) {
  const activeStatus = catalogs.statuses.find((item) => item.code === "ACTIVE")?.id ?? "";
  const [form, setForm] = useState<State>({ inversionistaId: "", vehiculoId: "", catalogContractTypeId: "", catalogContractStatusId: activeStatus, fechaInicio: "", fechaFin: "", montoMensual: "", montoCompra: "", observaciones: "" });
  const [errors, setErrors] = useState<Partial<Record<Field, string>>>({}); const [saving, setSaving] = useState(false);
  const vehicles = vehiculos.filter((item) => item.inversionistaId === form.inversionistaId); const selectedType = catalogs.types.find((item) => item.id === form.catalogContractTypeId);
  const update = (field: Field, value: string | File) => { setForm((old) => ({ ...old, [field]: value, ...(field === "inversionistaId" ? { vehiculoId: "" } : {}), ...(field === "catalogContractTypeId" && !catalogs.types.find((item) => item.id === value)?.allowsPurchase ? { montoCompra: "" } : {}) })); setErrors((old) => ({ ...old, [field]: undefined })); };
  const file = (value?: File) => { if (!value) return; if (!FILE_TYPES.includes(value.type)) return setErrors((old) => ({ ...old, archivo: "Adjunta un archivo PDF, JPG o PNG." })); if (value.size > MAX_SIZE) return setErrors((old) => ({ ...old, archivo: "El archivo no puede superar 5 MB." })); update("archivo", value); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (saving) return; const next: Partial<Record<Field, string>> = {}; if (!form.inversionistaId) next.inversionistaId = "Selecciona un inversionista."; if (!form.vehiculoId) next.vehiculoId = "Selecciona uno de sus vehículos."; if (!form.catalogContractTypeId) next.catalogContractTypeId = "Selecciona el tipo."; if (!form.catalogContractStatusId) next.catalogContractStatusId = "No existe un estado activo."; if (!form.fechaInicio) next.fechaInicio = "Selecciona la fecha de inicio."; if (!form.fechaFin) next.fechaFin = "Selecciona la fecha de fin."; else if (form.fechaInicio && form.fechaFin < form.fechaInicio) next.fechaFin = "No puede ser anterior a la fecha de inicio."; if (!form.montoMensual || Number(form.montoMensual) <= 0) next.montoMensual = "Ingresa un monto mensual válido."; if (selectedType?.allowsPurchase && (!form.montoCompra || Number(form.montoCompra) <= 0)) next.montoCompra = "Ingresa el monto de compra."; if (!form.archivo) next.archivo = "Adjunta el contrato digital."; setErrors(next); if (Object.keys(next).length || !form.archivo) return; setSaving(true); try { if (await onSave({ ...form, archivo: form.archivo })) onClose(); } finally { setSaving(false); } };
  const error = (name: Field) => errors[name] ? <span className="text-xs font-medium text-red-600">{errors[name]}</span> : null;
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/60 p-3" role="dialog" aria-modal="true"><form onSubmit={submit} className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><header className="sticky top-0 z-10 flex justify-between border-b bg-white p-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-400">Contratos</p><h2 className="mt-1 text-xl font-bold">Nuevo contrato</h2></div><button type="button" onClick={onClose} aria-label="Cerrar"><X /></button></header><div className="grid gap-4 p-5 sm:grid-cols-2">
    <label className="space-y-1.5"><span className="text-sm font-medium">Inversionista *</span><select value={form.inversionistaId} onChange={(e) => update("inversionistaId", e.target.value)} className={fieldClass(errors.inversionistaId)}><option value="">Seleccionar inversionista</option>{inversionistas.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select>{error("inversionistaId")}</label>
    <label className="space-y-1.5"><span className="text-sm font-medium">Vehículo *</span><select disabled={!form.inversionistaId || !vehicles.length} value={form.vehiculoId} onChange={(e) => update("vehiculoId", e.target.value)} className={`${fieldClass(errors.vehiculoId)} disabled:bg-slate-100`}><option value="">{!form.inversionistaId ? "Primero selecciona inversionista" : !vehicles.length ? "No tiene vehículos asociados" : "Seleccionar por placa"}</option>{vehicles.map((item) => <option key={item.id} value={item.id}>{item.placa} · {item.marca} {item.modelo}</option>)}</select>{error("vehiculoId")}</label>
    <label className="space-y-1.5"><span className="text-sm font-medium">Tipo de contrato *</span><select value={form.catalogContractTypeId} onChange={(e) => update("catalogContractTypeId", e.target.value)} className={fieldClass(errors.catalogContractTypeId)}><option value="">Seleccionar tipo</option>{catalogs.types.map((item) => <option key={item.id} value={item.id}>{item.name === "New" ? "Nuevo" : item.name === "Used" ? "Usado" : item.name}</option>)}</select>{error("catalogContractTypeId")}</label><div />
    <label className="space-y-1.5"><span className="text-sm font-medium">Fecha y hora de inicio *</span><input type="datetime-local" value={form.fechaInicio} onChange={(e) => update("fechaInicio", e.target.value)} className={fieldClass(errors.fechaInicio)} />{error("fechaInicio")}</label><label className="space-y-1.5"><span className="text-sm font-medium">Fecha y hora de fin *</span><input type="datetime-local" min={form.fechaInicio} value={form.fechaFin} onChange={(e) => update("fechaFin", e.target.value)} className={fieldClass(errors.fechaFin)} />{error("fechaFin")}</label>
    <label className="space-y-1.5"><span className="text-sm font-medium">Monto mensual (Bs) *</span><input type="number" min="0.01" step="0.01" value={form.montoMensual} onChange={(e) => update("montoMensual", e.target.value)} className={fieldClass(errors.montoMensual)} />{error("montoMensual")}</label>{selectedType?.allowsPurchase ? <label className="space-y-1.5"><span className="text-sm font-medium">Monto de compra (Bs) *</span><input type="number" min="0.01" step="0.01" value={form.montoCompra} onChange={(e) => update("montoCompra", e.target.value)} className={fieldClass(errors.montoCompra)} />{error("montoCompra")}</label> : <div className="space-y-1.5"><span className="text-sm font-medium">Monto de compra</span><div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 px-3.5 py-2.5 text-sm text-slate-500">{selectedType ? "No aplica para contratos usados" : "Selecciona primero el tipo de contrato"}</div></div>}
    <label className="space-y-1.5 sm:col-span-2"><span className="text-sm font-medium">Observaciones</span><textarea rows={3} value={form.observaciones} onChange={(e) => update("observaciones", e.target.value)} className={fieldClass()} /></label>
    <label className={`cursor-pointer rounded-2xl border-2 border-dashed p-5 text-center sm:col-span-2 ${errors.archivo ? "border-red-300" : "border-slate-300"}`}><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(e) => file(e.target.files?.[0])} className="sr-only" /><span className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-slate-950 text-white"><Upload className="h-5 w-5" /></span>{form.archivo ? <p className="mt-3 inline-flex items-center gap-2 text-sm font-semibold"><FileText className="h-4 w-4" />{form.archivo.name}</p> : <><p className="mt-3 text-sm font-semibold">Adjuntar contrato</p><p className="text-xs text-slate-500">PDF, JPG o PNG · máximo 5 MB</p></>}{error("archivo")}</label>
  </div><footer className="sticky bottom-0 flex justify-end gap-2 border-t bg-white p-5"><button type="button" onClick={onClose} disabled={saving} className="rounded-xl border px-5 py-2.5 text-sm font-semibold">Cancelar</button><button type="submit" disabled={saving || !activeStatus} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving && <LoaderCircle className="h-4 w-4 animate-spin" />}{saving ? "Guardando…" : "Guardar"}</button></footer></form></div>;
}
